### PR TITLE
Add Negative Prompt Feature

### PR DESCRIPTION
**Pull request by donlinglok**
Hi, I am immensely enjoying your project.

However, I have [heard that](https://rentry.co/8vaaa) there is also a "Negative Prompt" that can be input. 

I have checked the [diffusers source #1](https://github.com/huggingface/diffusers/blob/6b09f370c4184a89276c6891d17f45b9c8e8b4e5/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py) and [diffusers source #2](https://github.com/huggingface/diffusers/blob/3dcc75cbd4f924070cf9ebbbc1876ee04a0638c4/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py), and seems your project only need few change to implement it.

This request is my change and I have tested via colab.

Thanks again for your work!

### CODE REVIEW

**Comment by donlinglok** [comment]
Updates:

In current, the project are using `diffusers==0.3.0`, so [diffusers source #1](https://github.com/huggingface/diffusers/blob/6b09f370c4184a89276c6891d17f45b9c8e8b4e5/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py) is not valid, 
the correct source code is [diffusers source #3](https://github.com/huggingface/diffusers/blob/v0.3.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py).

Therefore, only `text2Img()` can support `negative_prompt` for now, we will need for the next diffuser release (0.3.1?) to use `negative_prompt` on `inpaint()`.

**Comment by lkwq007** [comment]
Seems that text2img also does not support the negative prompt with diffusers v0.3.0. Not sure when they will make the next release. https://github.com/huggingface/diffusers/blob/v0.3.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L94

**Comment by donlinglok** [comment]
Hum, you are right, 

Although I can run the text2Img() + negative_prompt without any error. 

But seems the negative_prompt didn't [work correctly](https://github.com/huggingface/diffusers/pull/549), I will do some tests again. Thank you for your reply!

**Comment by donlinglok** [comment]
Great news that diffusers just released 0.4.0 last night, I have tested the code in colab with test-case:

prompt=Bouquet of Roses
negative_prompt=red rose

**Comment by lkwq007** [comment]
Looks good to me. 
Thanks for this timely PR!

**Pull request merged**
